import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const google = localFont({
  src: [
    {
      path: "/fonts/Product Sans Regular.ttf",
    },
    {
      path: "/fonts/Product Sans Italic.ttf",
      style: "italic",
    },
    {
      path: "/fonts/Product Sans Bold.ttf",
      weight: "bold",
    },
    {
      path: "/fonts/Product Sans Bold Italic.ttf",
      weight: "bold",
      style: "italic",
    },
  ],
  variable: "--font-google",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aptinova",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} dark ${geistMono.variable} font-google ${google.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
